server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun6?characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: cloud-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:10086/eureka